# Generated by Django 3.1.5 on 2021-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pic',
            field=models.ImageField(blank=True, upload_to='blog/images'),
        ),
    ]
