# Generated by Django 3.1.5 on 2021-04-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
