# Generated by Django 3.1.5 on 2021-04-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinegames',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog/user_pics'),
        ),
    ]
