# Generated by Django 3.1.5 on 2021-04-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_onlinegames_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinegames',
            name='pic',
        ),
    ]
